### ISSUE TITLE
Error dropping table postgresql

### ISSUE THREAD

**Issue by kernie** [HEPData/hepdata#142]
Hi!

Started a local install of hepdata on Ubuntu 16.04 and followed the guide http://hepdata.readthedocs.io/en/latest/installation.html .

When it comes to executing the script "initialise_db.sh" it comes to an error that I cannot circumvent by setting "trust" in the "pg_hba.conf" in /etc/postgresql, see below.

Any idea?

Thanks,
Maarten

```
Do you know that you are going to drop the db? [y/N]: y
Dropping all tables!
  [#-----------------------------------]    2%
Traceback (most recent call last):
  File "/home/hepdata/.virtualenvs/hepdata/bin/hepdata", line 11, in <module>
    load_entry_point('hepdata', 'console_scripts', 'hepdata')()
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/invenio_db/cli.py", line 90, in drop
    table.drop(bind=_db.engine, checkfirst=True)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 772, in drop
    checkfirst=checkfirst)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1928, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1921, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/hepdata/.virtualenvs/hepdata/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied
```

**Comment by GraemeWatt** [comment]
This looks like an authentication problem.  A password should not be required after setting `trust` in the `pg_hba.conf` file.  Did you set `trust` for IPv4/IPv6 local connections?  Did you restart the PostgreSQL server after editing the `pg_hba.conf` file?

In future, please seek user support for problems like this by sending an email to info@hepdata.net.  The GitHub issues are more intended for reporting specific bugs in this repository.
